### ISSUE TITLE
Infinite Loop issue

### ISSUE THREAD

**Issue by usik** [aws-samples/visual-search-for-retail-with-amazon-bedrock-and-amazon-opensearch#1]
Hi team,

Under the section 2.B in this notebook ["visualsearch-with-amazontitan-and-anthropicclaude.ipynb" ](https://github.com/aws-samples/visual-search-for-retail-with-amazon-bedrock-and-amazon-opensearch-notebooks/blob/main/visualsearch-with-amazontitan-and-anthropicclaude.ipynb)

There is potential for infinite While loop.

```
def split_data(data, num_splits):
    avg = len(data) // num_splits
    out = []
    last = 0.0

    while last < len(data):
        out.append(data[int(last):int(last + avg)])
        last += avg

    return out
```

Suppose,

```
len(data) = 1
num_splits = 2

avg = 1 // 2, which results in avg = 0 and not avg = 0.5.
```

In the while loop,

```
last += avg will be 0.0 += 0.
```

So changing to float division from integer division should prevent the infinite loop.
```
avg = len(data) / num_splits
```

**Comment by Adibuer-lab** [comment]
Thanks very much for bringing this up, created a PR hoping to address it, let me know what you think
